### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rahulch** [playframework/play-scala-websocket-example#93]
Ran into the following error on `sbt run` as of commit : dad8d28dd69a42032c98884d64c63177c94050cb

```
Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which in some cases may be orders of magnitude slower than using node.js.
[info] CoffeeScript compiling on 1 source(s)
[info] LESS compiling on 1 source(s)
[error] Wrapped java.lang.ArrayIndexOutOfBoundsException: -30219 (module.js#439)Wrapped java.lang.ArrayIndexOutOfBoundsException: -30219
[error]     at module.js:439
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:364
[error]     at require (module.js:380)
[error]     at /Users/admin/Work/play-scala-websocket-example/project/target/node-modules/webjars/coffee-script/lib/coffee-script/coffee-script.js:14
[error]     at /Users/admin/Work/play-scala-websocket-example/project/target/node-modules/webjars/coffee-script/lib/coffee-script/coffee-script.js:2
[error]     at module.js:456
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:364
[error]     at require (module.js:380)
[error]     at /Users/admin/Work/play-scala-websocket-example/project/target/coffeescript/coffee.js:7
[error]     at /Users/admin/Work/play-scala-websocket-example/project/target/coffeescript/coffee.js:3
[error]     at module.js:456
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:497
[error]     at startup (trireme.js:142)
[error]     at trireme.js:923
[error] com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: Wrapped java.lang.ArrayIndexOutOfBoundsException: -30219 (module.js#439)Wrapped java.lang.ArrayIndexOutOfBoundsException: -30219
[error]     at module.js:439
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:364
[error]     at require (module.js:380)
[error]     at /Users/admin/Work/play-scala-websocket-example/project/target/node-modules/webjars/coffee-script/lib/coffee-script/coffee-script.js:14
[error]     at /Users/admin/Work/play-scala-websocket-example/project/target/node-modules/webjars/coffee-script/lib/coffee-script/coffee-script.js:2
[error]     at module.js:456
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:364
[error]     at require (module.js:380)
[error]     at /Users/admin/Work/play-scala-websocket-example/project/target/coffeescript/coffee.js:7
[error]     at /Users/admin/Work/play-scala-websocket-example/project/target/coffeescript/coffee.js:3
[error]     at module.js:456
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:497
[error]     at startup (trireme.js:142)
[error]     at trireme.js:923
[error] 
[error] 	at com.typesafe.sbt.jse.SbtJsTask$.$anonfun$executeJsOnEngine$1(SbtJsTask.scala:218)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
[error] 	at scala.util.Success.map(Try.scala:209)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by pereirazc** [comment]
I'm having the same issue. It also happens in the ef399f09066a4b0c030658ffd4fced859ca4cc55

**Comment by Robanvdd** [comment]
I'm running into the same issues, but I'm only compiling CoffeeScript.
Also, the errors dissapear when I'm using node.js

**Comment by stmi** [comment]
Same solution as above - I've installed node10 on my system and test/run work just fine.

**Comment by aknay** [comment]
The freshly downloaded WebSocket example still having the same issue. I can confirm that installing `node.js` solve this problem.
